// Generated by `supabase gen types typescript --local > types/database.ts`.
//
// Placeholder until Sprint 1 introduces the first migration. Once tables exist,
// regenerate this file and the Supabase clients will be fully typed.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
